### ISSUE TITLE
 Invalid_grant  on xero connection

### ISSUE THREAD

**Issue by bilalswiftsolutions** [webfox/laravel-xero-oauth2#48]
After Every few days i am getting this error .I don't know what is the reason behind it. i have tried everything created new organisation created new app cache:cleared . still getting this error. How I can connect it again?

**Comment by AllanGallop** [comment]
Seeing this too when trying to switch Xero users, presuming it is down to an expired refresh token I tried deleting out the xero.json but just hits with the 'Xero oauth credentials are missing' exemption. Any clues on how to clear out credentials and reconnect?

**Comment by bilalswiftsolutions** [comment]
When i deleted xero.json then i can reconnect it again. But now the issue is we don't it can be break anytime. without knowing reasong. our system is uploading invoices on xero automatically. and it starts failing because of this. is there any proper solution?

**Comment by hailwood** [comment]
Hi @bilalswiftsolutions & @AllanGallop,

Can you please tell me, is there a length of time between you using the Xero token? Or maybe does it always fail after 30 minutes?

The refresh tokens are supposed to be valid for 60 days so it shouldn't be expiring but I do wonder if that's the cause regardless and the Xero docs are wrong.

The fact you're getting invalid_grant errors is even stranger given that the logic for the refreshing of the tokens never changes.

I'm going to need a specific reproduction case to debug this. E.,g a certain time must pass without the token being used, or you need to make a specific call to trigger it otherwise I'm just guessing.

@sidneyAllen do you have any ideas?

**Comment by AllanGallop** [comment]
@hailwood 
Please excuse me, looks like a mistake on my end. A previous users revoked token was being passed instead of the new one by an error in my logic and call to ```getExpires``` outside the try/catch in the controller. I have additionally added logic to delete the JSON file and redirect the user to ```/xero/auth/authorize``` upon hitting an invalid grant and this has resolved my issues.

**Comment by hailwood** [comment]
Great to hear it's not a package issue for you @AllanGallop and thank you for following up :)

We'll keep this issue open for a bit longer to see if we can work out what's going on for @bilalswiftsolutions.

**Comment by bilalswiftsolutions** [comment]
hi @hailwood I don't know if it is issue on my side or not. 

Let me describe you scenario, I am not refreshing token anywhere don't know if it is wrong or not

I am using xero credentials on two places one is to manually upload invoice to xero

Which is working fine however it also gives error after few days. but not really early.

On second place I am using xero credentials to invoice upload automatically . This process is in queue. 

This how I am connecting xero app . Please let me know if anything is wrong here

```
 try {
           
            // Check if we've got any stored credentials
            if ($xeroCredentials->exists()) {
            
                /* 
                 * We have stored credentials so we can resolve the AccountingApi, 
                 * If we were sure we already had some stored credentials then we could just resolve this through the controller
                 * But since we use this route for the initial authentication we cannot be sure!
                 */
           
                $xero             = $this->authKey();
                $organisationName = $xero->getOrganisations($xeroCredentials->getTenantId())->getOrganisations()[0]->getName();
                $user             = $xeroCredentials->getUser();
                $username         = "{$user['given_name']} {$user['family_name']} ({$user['username']})";
               
            }
        } catch (\throwable $e) {
            // This can happen if the credentials have been revoked or there is an error with the organisation (e.g. it's expired)
            $error = $e->getMessage();
    
        }


        return view('web.admin.pages.xero', [
            'connected'        => $xeroCredentials->exists(),
            'error'            => $error ?? null,
            'organisationName' => $organisationName ?? null,
            'username'         => $username ?? null
        ]);
```

And here is how I am using it in laravel job (queued process)

```
<?php

namespace App\Jobs\Invoice;

use App\Http\Controllers\Admin\Contacts\CustomerController;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use App\Models\Admin\Invoice;
use App\Services\Contacts\CustomerSettingService;
use Webfox\Xero\OauthCredentialManager;
class UploadInvoiceToXero implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    protected $invoice_id;


    public function __construct($invoice_id)
    {
        $this->invoice_id = $invoice_id;
     
   
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle(OauthCredentialManager $xeroCredential)
    {
        CustomerController::uploadAutoInvoiceToXero($this->invoice_id, $xeroCredential);

    }
}

```
I don't know If i need to refresh token here or not.
Please let me know if i am doing anything wrong here

**Comment by hailwood** [comment]
Hmm,

That looks fine to me. And you shouldn't need to refresh the token.

Every time the credential manager is resolved from the container it should
be refreshing it for you.

**Comment by bilalswiftsolutions** [comment]
it is creating issue in Queue process I don't know why

**Comment by hailwood** [comment]
Just checking, what version are you using? As the old versions didn't resolve it each time, they should on the new versions though.

**Comment by bilalswiftsolutions** [comment]
no its latest version 2.0.*

**Comment by hailwood** [comment]
I really have no idea then sorry. Unless I can get a solid reproduction case there's not a lot I can do.

**Comment by bilalswiftsolutions** [comment]
reproduction is easy. Just use it in queue process

**Comment by hailwood** [comment]
I just re-read over your code and noticed you never seem to resolve the AccountingApi or IdentityApi so in turn never resolve the Configuration object from Xero.

I've moved the token refresh logic to happen when you resolve the credential manager.
Give that a go and let me know if it's still an issue :) v2.0.5

**Comment by bilalswiftsolutions** [comment]
ok let me check that

**Comment by bilalswiftsolutions** [comment]
ok its working fine now. Thanks a lot. it gives error after 2 to 3 days . I will reopen issue if I get any other error

**Comment by bilalswiftsolutions** [comment]
Again I got this error while i was uploading to xero 

```

League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222
--
Stack trace:
#0 /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))


```
But on next try it work fine. what could be the reason?

**Comment by hailwood** [comment]
Can I please have a full stack trace?
I need to see what's triggering the Oauth2 provider to try the grant.

**Comment by bilalswiftsolutions** [comment]
here is the full trace 

```

League\OAuth2\Client\Provider\Exception\IdentityProviderException: invalid_grant in /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/GenericProvider.php:222
--
Stack trace:
#0 /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\GenericProvider->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 /var/www/html/coldxlogistics/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 /var/www/html/coldxlogistics/vendor/webfox/laravel-xero-oauth2/src/Oauth2CredentialManagers/FileStore.php(86): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array)
#3 /var/www/html/coldxlogistics/vendor/webfox/laravel-xero-oauth2/src/XeroServiceProvider.php(58): Webfox\Xero\Oauth2CredentialManagers\FileStore->refresh()
#4 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Container.php(826): Webfox\Xero\XeroServiceProvider->Webfox\Xero\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Container.php(712): Illuminate\Container\Container->build(Object(Closure))
#6 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(826): Illuminate\Container\Container->resolve('Webfox\\Xero\\Oau...', Array, true)
#7 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Foundation\Application->resolve('Webfox\\Xero\\Oau...', Array)
#8 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(811): Illuminate\Container\Container->make('Webfox\\Xero\\Oau...', Array)
#9 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(173): Illuminate\Foundation\Application->make('Webfox\\Xero\\Oau...')
#10 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(124): Illuminate\Container\BoundMethod::addDependencyForCallParameter(Object(Illuminate\Foundation\Application), Object(ReflectionParameter), Array, Array)
#11 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Container\BoundMethod::getMethodDependencies(Object(Illuminate\Foundation\Application), Array, Array)
#12 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#14 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#15 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#16 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call(Array)
#17 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\Invoice\UploadInvoiceToXero))
#18 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\Invoice\UploadInvoiceToXero))
#19 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(118): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\Invoice\UploadInvoiceToXero), false)
#21 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}(Object(App\Jobs\Invoice\UploadInvoiceToXero))
#22 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\Invoice\UploadInvoiceToXero))
#23 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(120): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(70): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware(Object(Illuminate\Queue\Jobs\RedisJob), Object(App\Jobs\Invoice\UploadInvoiceToXero))
#25 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\RedisJob), Array)
#26 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#27 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process('redis', Object(Illuminate\Queue\Jobs\RedisJob), Object(Illuminate\Queue\WorkerOptions))
#28 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob(Object(Illuminate\Queue\Jobs\RedisJob), 'redis', Object(Illuminate\Queue\WorkerOptions))
#29 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon('redis', 'invoice', Object(Illuminate\Queue\WorkerOptions))
#30 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker('redis', 'invoice')
#31 /var/www/html/coldxlogistics/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#32 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#33 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#35 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#36 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#37 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call(Array)
#38 /var/www/html/coldxlogistics/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#39 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#40 /var/www/html/coldxlogistics/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#41 /var/www/html/coldxlogistics/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand(Object(Laravel\Horizon\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#42 /var/www/html/coldxlogistics/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#43 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#44 /var/www/html/coldxlogistics/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/html/coldxlogistics/artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 {main}
```

I am using these scopes 

```
 'scopes'                     => [
            'openid',
            'email',
            'profile',
            'offline_access',
            'accounting.settings',
            'accounting.contacts',
            'accounting.transactions'
        ],

```

Yesterday it was connected to xero. Today when I came back to office application was disconnected and it was showing same invalid grant error. 

I am using default Credential manager didn't customize anything. 
I will let you after checking latest version

**Comment by bilalswiftsolutions** [comment]
have you find anything? it is giving error of invalid_grant on daily basis

**Comment by hailwood** [comment]
I think this is one you'll need to contact Xero support to see what's going on from their logs unfortunately.
Everything looks normal from that stack trace.

**Comment by bilalswiftsolutions** [comment]
do we need avoid some kind of commands or need to give permissions?

**Comment by tadevosyankhachik** [comment]
@bilalswiftsolutions I have the same issue.
I there any solution?
